export const EDITOR_UI_CONSTANTS = {
  CANVAS_WIDTH_RATIO: 0.8,
  CANVAS_MAX_SCALE: 5,
  CANVAS_MIN_SCALE: 0.5,
  FLOATING_BTN_OFFSET: -50,
  FLOATING_BTN_SIZE: 40,
  BOTTOM_BAR_HEIGHT: 100,
  CENTER_ADD_BTN_SIZE: 58,
  MODAL_BORDER_RADIUS: 28,
  MODAL_MIN_HEIGHT: 400,
  ITEM_ICON_SIZE: 66,
  ITEM_BADGE_COLOR: "#EECB68",
  ITEM_NEW_COLOR: "#007AFF",
};
