import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "flex-end",
  },
  container: {
    backgroundColor: "#121212",
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    height: "88%",
    paddingBottom: 30,
    borderWidth: 1,
    borderColor: "#222",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 20,
    paddingHorizontal: 20,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.5,
  },

  tabSwitcher: {
    flexDirection: "row",
    backgroundColor: "#1c1c1c",
    borderRadius: 14,
    marginHorizontal: 60,
    height: 48,
    padding: 4,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#2a2a2a",
  },
  tabActive: {
    flex: 1,
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 4,
    elevation: 5,
  },
  tabInactive: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  tabTextActive: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "700",
  },
  tabTextInactive: {
    color: "#777",
    fontSize: 15,
    fontWeight: "500",
  },
  crownContainer: {
    marginLeft: 8,
    backgroundColor: "#FFD700",
    borderRadius: 12,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#000",
  },
  previewContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 10,
  },
  previewFrame: {
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.6,
    shadowRadius: 30,
    elevation: 25,
    borderRadius: 12,
    overflow: "hidden",
    position: "relative",
    borderWidth: 1,
    borderColor: "#333",
  },
  expandBtn: {
    position: "absolute",
    bottom: 16,
    left: 16,
    backgroundColor: "rgba(0,0,0,0.75)",
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.2)",
  },
  optionsScroll: {
    paddingHorizontal: 24,
    alignItems: "center",
  },
  footer: {
    paddingTop: 10,
    borderTopWidth: 1,
    borderColor: "#222",
  },
});
