import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "#111",
    justifyContent: "space-between",
    paddingTop: 50,
    paddingBottom: 40,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    letterSpacing: 0.5,
  },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
  },
  tabSwitcher: {
    flexDirection: "row",
    backgroundColor: "#2c2c2e",
    borderRadius: 10,
    marginHorizontal: "24%",
    height: 40,
    padding: 3,
    marginBottom: 20,
  },
  tabActive: {
    flex: 1,
    backgroundColor: "#666",
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  tabInactive: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
  },
  tabTextActive: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  tabTextInactive: {
    color: "#aaa",
    fontSize: 14,
    fontWeight: "500",
  },
  crownContainer: {
    position: "absolute",
    top: -12,
    right: 4,
    backgroundColor: "#FFD700",
    borderRadius: 12,
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  previewContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  previewCard: {
    backgroundColor: "#fff",
    padding: 40,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  previewFrame: {
    backgroundColor: "#fff",
    position: "relative",
  },
  expandBtn: {
    position: "absolute",
    bottom: -25,
    left: -25,
    backgroundColor: "#333",
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
  },
  dotsContainer: {
    flexDirection: "row",
    marginTop: 30,
    gap: 8,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  dotActive: {
    backgroundColor: "#fff",
  },
  dotInactive: {
    backgroundColor: "#555",
  },
  optionsScroll: {
    paddingHorizontal: 20,
    alignItems: "center",
  },
  footer: {
    paddingTop: 10,
  },
});
