name: Mobile CI

on:
  push:
    branches: [ "main", "dev" ]
    paths:
      - 'feSCRL/**'
      - '.github/workflows/mobile-ci.yml'
  pull_request:
    branches: [ "main", "dev" ]
    paths:
      - 'feSCRL/**'

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: './feSCRL/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./feSCRL
      run: npm ci
      
    - name: Run Expo Lint
      working-directory: ./feSCRL
      run: npm run lint
